# @package encoder
_target_: fewie.encoders.contrastive.ContrastiveTransformerEncoder
model_name_or_path: SpanBERT/spanbert-base-cased
# options: bert-base-uncased, xlnet-base-cased, SpanBERT/spanbert-base-cased
#          albert-base-v2, roberta-base
