seed: 1234
cuda_device: 0
batch_size: 1
use_vae: False
vae_epochs: 1
text_column_name: tokens
label_column_name: ner_tags
scenario:
  name: few_shot_linear_readout
  metrics:
    - accuracy
    - f1_micro
    - f1_macro

defaults:
  - dataset: conll2003
  - dataset_processor: transformer
  - encoder: random
  - evaluation/dataset: nway_kshot
  - evaluation/classifier: logistic_regression
