seed: 1234
cuda_device: 0
batch_size: 1
text_column_name: tokens
label_column_name: ner_tags
scenario:
  name: few_shot_contrastive_pretraining
  metrics:
    - accuracy
    - f1_micro
    - f1_macro

defaults:
  - dataset: conll2003
  - dataset_processor: bert
  - encoder: contrastive
  - evaluation/dataset: contrastive_nway_kshot
  - evaluation/classifier: logistic_regression

# optional: involved in contrastive pre-training
num_epochs: 1
learning_rate: 0.0001
weight_decay: 0