seed: 1234
cuda_device: 0
batch_size: 1
text_column_name: tokens
label_column_name: course_tags
scenario:
  name: few_shot_linear_readout
  metrics:
    - accuracy
    - f1_micro
    - f1_macro

defaults:
  - dataset: fewnerd
  - dataset_processor: roberta
  - encoder: roberta
  - evaluation/dataset: nway_kshot_5_1
  - evaluation/classifier: logistic_regression
