# @package dataset_processor
# This script provides the baseline for bert-ner

_target_: fewie.dataset_processors.transformer.TransformerProcessor
tokenizer_name_or_path: bert-base-cased
max_length: 128
label_all_tokens: false
